### ISSUE TITLE
Hi for the links

### ISSUE THREAD

**Issue by johnnliu** [markheath/azure-functions-links#1]
[@ling_toh](https://twitter.com/ling_toh) is on AzureFunctions team - seems to be the person most responsible for PowerShell, but also does other things.

On PowerShell:

[@AlexVerkinderen](https://twitter.com/AlexVerkinderen) blogged about AF with PowerShell and Azure Active Directory (AAD).  http://www.mscloud.be/retrieve-azure-aad-user-information-with-azure-functions-and-publish-it-into-powerbi/

[@johnnliu](https://twitter.com/johnnliu) blogged about AF with PowerShell, SharePoint Online and Office 365.  http://johnliu.net/blog/2016/11/build-your-pnp-site-provisioning-with-powershell-in-azure-functions-and-run-it-from-flow

**Comment by justinyoo** [comment]
Here are another links:
- [Azure Functions Deployment Strategies](https://blog.kloud.com.au/2016/09/04/azure-functions-deployment-strategies/) by [@justinchronicle](https://twitter.com/justinchrinocle)
- [Testing Azure Functions in Emulated Environment with ScriptCs](https://blog.kloud.com.au/2016/09/05/testing-azure-functions-in-emulated-environment-with-scriptcs/) by [@justinchronicle](https://twitter.com/justinchrinocle)
- [NuGet package for Azure Functions emulation](https://www.nuget.org/packages/ScriptCs.AzureFunctions)

**Acknowledgement** I'm the author of all above.

**Comment by markheath** [comment]
thanks, will have a read and update my list
