### ISSUE TITLE
Help with Arm Templates and identity verification 

### ISSUE THREAD

**Issue by neilonetwo** [markheath/azure-functions-links#4]
Hi Mark

I have been looking everywhere for this answer but can’t seem to find it anywhere and you seem to be the expert on this so was hoping you might be able to help

I have an ARM template that deploys azure function infrastructure and I have been trying to add an identity section to the template so that it can connect to a DB via AAD (picking up a token) however the deployment process does not have the privileges to create AAD groups or assign principal Id’s to groups.  The Admin has given me a service principal id with the privileges to access the database but I can’t seem to find a way of attaching this principal Id to the infrastructure if I chose the identity type to be systemAssigned then I can’t add the principal id as a field and if I take the type out then the template fails do you know how the finction infrastructure can take on the principal Id that I have been given ?

Sorry to bother you but hopefully you can help

Thanks Neil

**Comment by markheath** [comment]
sorry that's not something I've done before with ARM templates. Most of my ARM knowledge I've gained by looking through the sample templates here: https://github.com/Azure/azure-quickstart-templates, so maybe you can find something that helps you there.
